include:
  - _next
  - _next/_LOCylIVKNrRPvTGKfLIZ
  - _next/_LOCylIVKNrRPvTGKfLIZ/_buildManifest.js
  - _next/_LOCylIVKNrRPvTGKfLIZ/ssgManifest.js
  - _next/chunks/pages/_app-fc42de40e8b2cce3.js
  - _next/chunks/pages/_error-7ddc2730f944d98a.js